services:
  database:
    image: postgres:15-alpine
    container_name: agm_database_extractor
    environment:
      - DATABASE_NAME=extractor_db
      - DATABASE_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./agm-extractor-backend/
      dockerfile: Dockerfile
    container_name: agm_backend
    env_file:
      - ./agm-extractor-backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - database


  frontend:
    build:
      context: ./agm-extractor-fronted/
      dockerfile: Dockerfile
    container_name: agm_frontend
    ports:
      - "5174:80"
    env_file:
      - ./agm-extractor-fronted/.env
    depends_on:
      - backend

volumes:
  pgdata:
